name: ManhuntPlugin
main: juraff.minecraft.manhunt.Manhunt
version: 1.0
api-version: 1.13
commands:
   test:
      description: tests the plugin
      usage: /test
      # permissions: your.permission here
   team:
      description: manages team
      usage: /team <other-command>